# role constants
ROLE_ADMIN = 1
ROLE_RECEPTIONIST = 2
ROLE_CUSTOMER = 3

# booking statuses
BOOKING_STATUS_PENDING = 1
BOOKING_STATUS_CONFIRMED = 2
BOOKING_STATUS_CANCELLED = 3

# payment methods
PAYMENT_METHOD_CASH = 1
PAYMENT_METHOD_CARD = 2
PAYMENT_METHOD_BANK_TRANSFER = 3

# room status
ROOM_STATUS_AVAILABLE = 1
ROOM_STATUS_DIRTY = 2
ROOM_STATUS_OUT_OF_SERVICE = 3

# room type
ROOM_TYPE_STANDART = 1
ROOM_TYPE_SUPERIOR = 2
ROOM_TYPE_DELUXE = 3
ROOM_TYPE_FAMILY = 4
ROOM_TYPE_SUITE = 5